### ISSUE TITLE
Wrong bounding box when the vehicle turns. (probably rotation issue)

### ISSUE THREAD

**Issue by makaveli10** [mesakh123/CarlaSimulatorKitti#10]
Hi,
Thanks for sharing your work. I found that the vehicles which are turning have their bounding box rotated in a different direction when plotted via [simple_kitti_visualization](https://github.com/zzzxxxttt/simple_kitti_visualization): 
For eg.
![mayavi](https://user-images.githubusercontent.com/39617050/172867400-3268bcd9-1057-4995-abe6-aefe041c9c6c.png)

The vehicles which have no rotation in the ```yaw``` axis work fine. I hope you are able to reproduce this on your end. Let me know if you dont.
Thanks

**Comment by mesakh123** [comment]
sorry, i was busy lately. I havent testing the the function clearly after some modification, i would try to test whether there is any wrong modification
