### ISSUE TITLE
Where will the SynchronousClient.py be used?

### ISSUE THREAD

**Issue by AOOOOOA** [mesakh123/CarlaSimulatorKitti#8]
Hi,

Thanks for your great work, it helps me a lot.

I had a question about where will the ***SynchronousClient.py*** be used? Since I found that some functions inside it are similar to those in ***SynchronyModel.py***. And I didn't find the direct call in generator.py

Thanks

**Comment by christianmasa** [comment]
Hi,

it's great to hear the repo helps. I forgot to delete SynchronousClient.py since i did some modification and saved it on SynchronyModel.py . You could ignore SynchronousClient.py .

**Comment by AOOOOOA** [comment]
> Hi,
> 
> it's great to hear the repo helps. I forgot to delete SynchronousClient.py since i did some modification and saved it on SynchronyModel.py . You could ignore SynchronousClient.py .

Thanks!
