### ISSUE TITLE
 The R and T matrix in calib files

### ISSUE THREAD

**Issue by AOOOOOA** [mesakh123/CarlaSimulatorKitti#9]
Thanks for your quick and kindly reply to my last question!

I have a few questions about the R and T matrix in calib files. Since I found out that the P0, P1..., R0_rect, Tr_velo_to_cam, and Tr_imu_to_velo in all calib files are the same. Are they the real value in Carla world that can be directly used or just some pre-defined values?

**Comment by AOOOOOA** [comment]
I have found the answer to this question from the code.

**Comment by mesakh123** [comment]
sorry, i was busy this days
